server:
  port: 9001
spring:
  application:
    name: CHUYENBAY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/QLSanBay
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update  #từ động đồng bộ model với database
    generate-ddl: true
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:7000/eureka/
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      maybayServiceCircuitb:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      maybayService:
        maxAttempts: 3
        waitDuration: 10s

